### ISSUE TITLE
Needs go 1.16

### ISSUE THREAD

**Issue by clach04** [siviae/gitjournal-simplenote-exporter#1]
C:\code\go\gitjournal-simplenote-exporter>go run main.go --help
    go: downloading github.com/buger/jsonparser v1.1.1
    go: downloading github.com/go-git/go-git/v5 v5.2.0
    go: downloading github.com/go-git/go-billy/v5 v5.0.0
    go: downloading golang.org/x/crypto v0.0.0-20200302210943-78000ba7a073
    go: downloading github.com/sergi/go-diff v1.1.0
    go: downloading github.com/mitchellh/go-homedir v1.1.0
    go: downloading github.com/emirpasic/gods v1.12.0
    go: downloading github.com/imdario/mergo v0.3.9
    go: downloading golang.org/x/net v0.0.0-20200301022130-244492dfa37a
    go: downloading github.com/xanzy/ssh-agent v0.2.1
    go: downloading github.com/jbenet/go-context v0.0.0-20150711004518-d14ea06fba99
    go: downloading github.com/kevinburke/ssh_config v0.0.0-20190725054713-01f96b0aa0cd
    go: downloading golang.org/x/sys v0.0.0-20200302150141-5c8b2ff67527
    go: downloading github.com/go-git/gcfg v1.5.0
    go: downloading gopkg.in/warnings.v0 v0.1.2
    # command-line-arguments
    .\main.go:168:15: undefined: io.ReadAll
    note: module requires Go 1.16

**Comment by clach04** [comment]
Builds with go1.20.5 :-)
